sudo: false
language: go
go:
- 1.10.x
- master

go_import_path: github.com/improbable-eng/thanos

install:
- openssl aes-256-cbc -K $encrypted_df79f74ec4fb_key -iv $encrypted_df79f74ec4fb_iv
  -in test/travis-gcs-creds.json.enc -out ${GOPATH}/src/github.com/improbable-eng/thanos/travis-gcs-creds.json -d
- make install-tools
- dep ensure

script:
- make format test
